defmodule Checkers.Schemas.User do
  @moduledoc """
  User schema.
  Generated by Pow.
  """
  use Ecto.Schema
  use Pow.Ecto.Schema
  use Pow.Extension.Ecto.Schema, extensions: [PowResetPassword]

  import Ecto.Changeset

  @type t :: %__MODULE__{}

  schema "users" do
    field :login, :string
    pow_user_fields()

    timestamps()
  end

  @typep user_or_changeset :: t() | Ecto.Changeset.t()

  @doc false
  @spec changeset(user_or_changeset, map) :: Ecto.Changeset.t()
  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
    |> cast(attrs, [:login])
    |> validate_required([:login])
  end
end
